name: First Workflow 
on: workflow_dispath

jobs: 
  first-job: 
    runs-on: ubunto-latests
    steps: 
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
 
